#password is hashed 123456789
apiVersion: v1
stringData:
  user-configuration.json: '{
 "user": [
  {
    "name": "machine-user-1",
    "password": "$6$cC.frL8fd1LS8ci4$OuvXjkRW.D6BawV8wt0dtDSVFynMDB99/6jv/2y6ip95mMs/1NMjhJRsm8NDF0fBTLXncjPRqTTBPjizok4Mg0",
    "groups": [
         "nrf-admin",
         "nrf-security-admin",
         "nssf-admin",
         "nssf-security-admin",
         "nrfagent-admin",
         "nrfagent-security-admin",
         "sragent-admin"
    ]
   }
 ]
}'
kind: Secret
metadata:
  labels:
    applicable-for: eric-ccrc
  name: eric-sec-admin-user-management-day0-user
type: Opaque
