#password is hashed 123456789
apiVersion: v1
stringData:
  user-configuration.json: '{
 "user": [
  {
    "name": "machine-user-1",
    "password": "$6$cC.frL8fd1LS8ci4$OuvXjkRW.D6BawV8wt0dtDSVFynMDB99/6jv/2y6ip95mMs/1NMjhJRsm8NDF0fBTLXncjPRqTTBPjizok4Mg0",
    "groups": [
        "ccsm-admin",
        "system-admin",
        "ausf_admin",
        "udm_admin",
        "eir_admin",
        "hssepc_admin",
        "hssims_admin",
        "nrfagent-admin"
    ]
   }
 ]
}'
kind: Secret
metadata:
  labels:
    applicable-for: eric-ccsm
  name: eric-sec-admin-user-management-day0-user
type: Opaque
