apiVersion: v1
stringData:
  eric-sec-certm-deployment-config.json: '{
    "pkcs12": [
        {
            "name": "pkcs12Key",
            "certificate-name": "certificate",
            "pkcs12": "pkcs12Binary",
            "password": "password"
        }
    ]
    "ca-certs": [
        {
            "name": "trustedCerts",
            "pem": "pemBinaries"
        }
    ]
}'
kind: Secret
metadata:
  labels:
    applicable-for: eric-ccdm
  name: eric-sec-certm-deployment-config
type: Opaque
