apiVersion: v1
stringData:
  ldap-config.json: '{
  "server": [
    {
      "name" : "externalLdapName",
      "tcp":
      {
        "address": "external.ldap.server.com",
        "ldap":
        {
          "port": 389
        },
        "ldaps":
        {
          "port": 636
        }
      }
    }
  ],
  "security":
  {
    "user-base-dn": "ou=people,dc=mycompany,dc=com",
    "simple-authenticated":
    {
      "bind-dn": "uid=client-bind-admin,ou=people,dc=mycompany,dc=com",
      "bind-password": "cleartext-bind-password"
    }
  },
  "options":
  {
      "timeout": 10,
      "enable-referrals": true
  }
}'
kind: Secret
metadata:
  labels:
    applicable-for: eric-ccdm
  name: eric-sec-aum-external-ldap
type: Opaque
