apiVersion: v1
stringData:
  config.json: '{
  "trapTargets": [
    {
      "address": "1.2.3.4",
      "user": "udmuser",
      "securityLevel": "authPriv",
      "authPassphrase": "myAuthPassword",
      "authProtocol": "SHA1",
      "privPassphrase": "myPrivPassword",
      "privProtocol": "AES128"
    }
  ]
}'
kind: Secret
metadata:
  labels:
    applicable-for: eric-cces.eric-ccrc
  name: snmp-alarm-provider-config
type: Opaque
