#admin, encoded with base64
apiVersion: v1
stringData:
  etcdpasswd: YWRtaW4=
kind: Secret
metadata:
  labels:
    applicable-for: eric-ccdm.eric-ccsm.eric-ccrc.eric-ccpc.eric-cces
  name: eric-data-distributed-coordinator-creds
type: Opaque
