apiVersion: v1
stringData:
  config.json: '{
  "kafkaAddress": "eric-udr-message-bus-kf", "kafkaPort": 9093,
  "trapTargets": [
    {"address":"1.2.3.4","port":8081,"community":"public"},
    {"address":"1.2.3.4","port":162,"community":"public"}
]}'
kind: Secret
metadata:
  labels:
    applicable-for: eric-ccdm
  name: snmp-alarm-provider-config
type: Opaque
